# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dafee8292f6662a3e133786769c624d7f4df41518f48a4e4e169a904d87b9e6e4eafda7459aa753cfeb0ea3bdce83268f45579020a1ae3dd01690f0c3ec959cf

test:
  secret_key_base: bfefade94f4573c2d6293a7cc04f6458eff2ccfd23d534ade187201346e44862f1c38dedbcb5c6c697b770c3d9542f9dd4fd0183f9dbbbcc25569cb54fb4df8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
